package com.longruan.zmsys.models;

public class ApiError {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_error.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_error.code
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_error.des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String des;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_error.id
	 * @return  the value of api_error.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_error.id
	 * @param id  the value for api_error.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_error.code
	 * @return  the value of api_error.code
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_error.code
	 * @param code  the value for api_error.code
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_error.des
	 * @return  the value of api_error.des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_error.des
	 * @param des  the value for api_error.des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setDes(String des) {
		this.des = des;
	}
}