package com.longruan.zmsys.models;

public class ApiReqParam {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.req_url_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer reqUrlId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.req_field
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqField;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.req_type
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.req_des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqDes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.req_required
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqRequired;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.req_def_val
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqDefVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_param.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.id
	 * @return  the value of api_req_param.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.id
	 * @param id  the value for api_req_param.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.req_url_id
	 * @return  the value of api_req_param.req_url_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getReqUrlId() {
		return reqUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.req_url_id
	 * @param reqUrlId  the value for api_req_param.req_url_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqUrlId(Integer reqUrlId) {
		this.reqUrlId = reqUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.req_field
	 * @return  the value of api_req_param.req_field
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqField() {
		return reqField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.req_field
	 * @param reqField  the value for api_req_param.req_field
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqField(String reqField) {
		this.reqField = reqField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.req_type
	 * @return  the value of api_req_param.req_type
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqType() {
		return reqType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.req_type
	 * @param reqType  the value for api_req_param.req_type
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqType(String reqType) {
		this.reqType = reqType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.req_des
	 * @return  the value of api_req_param.req_des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqDes() {
		return reqDes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.req_des
	 * @param reqDes  the value for api_req_param.req_des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqDes(String reqDes) {
		this.reqDes = reqDes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.req_required
	 * @return  the value of api_req_param.req_required
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqRequired() {
		return reqRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.req_required
	 * @param reqRequired  the value for api_req_param.req_required
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqRequired(String reqRequired) {
		this.reqRequired = reqRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.req_def_val
	 * @return  the value of api_req_param.req_def_val
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqDefVal() {
		return reqDefVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.req_def_val
	 * @param reqDefVal  the value for api_req_param.req_def_val
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqDefVal(String reqDefVal) {
		this.reqDefVal = reqDefVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_param.remark
	 * @return  the value of api_req_param.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_param.remark
	 * @param remark  the value for api_req_param.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}