package com.longruan.zmsys.models;

public class ApiReqUrl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.module_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.req_title
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.req_base_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqBaseUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.req_type
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String reqType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.res_result
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String resResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.param_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer paramId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_req_url.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.id
	 * @return  the value of api_req_url.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.id
	 * @param id  the value for api_req_url.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.module_id
	 * @return  the value of api_req_url.module_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.module_id
	 * @param moduleId  the value for api_req_url.module_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.req_title
	 * @return  the value of api_req_url.req_title
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqTitle() {
		return reqTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.req_title
	 * @param reqTitle  the value for api_req_url.req_title
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqTitle(String reqTitle) {
		this.reqTitle = reqTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.req_base_url
	 * @return  the value of api_req_url.req_base_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqBaseUrl() {
		return reqBaseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.req_base_url
	 * @param reqBaseUrl  the value for api_req_url.req_base_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqBaseUrl(String reqBaseUrl) {
		this.reqBaseUrl = reqBaseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.req_url
	 * @return  the value of api_req_url.req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqUrl() {
		return reqUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.req_url
	 * @param reqUrl  the value for api_req_url.req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqUrl(String reqUrl) {
		this.reqUrl = reqUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.req_type
	 * @return  the value of api_req_url.req_type
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getReqType() {
		return reqType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.req_type
	 * @param reqType  the value for api_req_url.req_type
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setReqType(String reqType) {
		this.reqType = reqType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.res_result
	 * @return  the value of api_req_url.res_result
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getResResult() {
		return resResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.res_result
	 * @param resResult  the value for api_req_url.res_result
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setResResult(String resResult) {
		this.resResult = resResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.param_id
	 * @return  the value of api_req_url.param_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getParamId() {
		return paramId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.param_id
	 * @param paramId  the value for api_req_url.param_id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setParamId(Integer paramId) {
		this.paramId = paramId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_req_url.remark
	 * @return  the value of api_req_url.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_req_url.remark
	 * @param remark  the value for api_req_url.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}