package com.longruan.zmsys.models;

import java.util.ArrayList;
import java.util.List;

public class ApiReqUrlExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public ApiReqUrlExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andModuleIdIsNull() {
			addCriterion("module_id is null");
			return (Criteria) this;
		}

		public Criteria andModuleIdIsNotNull() {
			addCriterion("module_id is not null");
			return (Criteria) this;
		}

		public Criteria andModuleIdEqualTo(Integer value) {
			addCriterion("module_id =", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotEqualTo(Integer value) {
			addCriterion("module_id <>", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThan(Integer value) {
			addCriterion("module_id >", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("module_id >=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThan(Integer value) {
			addCriterion("module_id <", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThanOrEqualTo(Integer value) {
			addCriterion("module_id <=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdIn(List<Integer> values) {
			addCriterion("module_id in", values, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotIn(List<Integer> values) {
			addCriterion("module_id not in", values, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdBetween(Integer value1, Integer value2) {
			addCriterion("module_id between", value1, value2, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("module_id not between", value1, value2, "moduleId");
			return (Criteria) this;
		}

		public Criteria andReqTitleIsNull() {
			addCriterion("req_title is null");
			return (Criteria) this;
		}

		public Criteria andReqTitleIsNotNull() {
			addCriterion("req_title is not null");
			return (Criteria) this;
		}

		public Criteria andReqTitleEqualTo(String value) {
			addCriterion("req_title =", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleNotEqualTo(String value) {
			addCriterion("req_title <>", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleGreaterThan(String value) {
			addCriterion("req_title >", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleGreaterThanOrEqualTo(String value) {
			addCriterion("req_title >=", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleLessThan(String value) {
			addCriterion("req_title <", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleLessThanOrEqualTo(String value) {
			addCriterion("req_title <=", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleLike(String value) {
			addCriterion("req_title like", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleNotLike(String value) {
			addCriterion("req_title not like", value, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleIn(List<String> values) {
			addCriterion("req_title in", values, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleNotIn(List<String> values) {
			addCriterion("req_title not in", values, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleBetween(String value1, String value2) {
			addCriterion("req_title between", value1, value2, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqTitleNotBetween(String value1, String value2) {
			addCriterion("req_title not between", value1, value2, "reqTitle");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlIsNull() {
			addCriterion("req_base_url is null");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlIsNotNull() {
			addCriterion("req_base_url is not null");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlEqualTo(String value) {
			addCriterion("req_base_url =", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlNotEqualTo(String value) {
			addCriterion("req_base_url <>", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlGreaterThan(String value) {
			addCriterion("req_base_url >", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlGreaterThanOrEqualTo(String value) {
			addCriterion("req_base_url >=", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlLessThan(String value) {
			addCriterion("req_base_url <", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlLessThanOrEqualTo(String value) {
			addCriterion("req_base_url <=", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlLike(String value) {
			addCriterion("req_base_url like", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlNotLike(String value) {
			addCriterion("req_base_url not like", value, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlIn(List<String> values) {
			addCriterion("req_base_url in", values, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlNotIn(List<String> values) {
			addCriterion("req_base_url not in", values, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlBetween(String value1, String value2) {
			addCriterion("req_base_url between", value1, value2, "reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqBaseUrlNotBetween(String value1, String value2) {
			addCriterion("req_base_url not between", value1, value2,
					"reqBaseUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlIsNull() {
			addCriterion("req_url is null");
			return (Criteria) this;
		}

		public Criteria andReqUrlIsNotNull() {
			addCriterion("req_url is not null");
			return (Criteria) this;
		}

		public Criteria andReqUrlEqualTo(String value) {
			addCriterion("req_url =", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlNotEqualTo(String value) {
			addCriterion("req_url <>", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlGreaterThan(String value) {
			addCriterion("req_url >", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlGreaterThanOrEqualTo(String value) {
			addCriterion("req_url >=", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlLessThan(String value) {
			addCriterion("req_url <", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlLessThanOrEqualTo(String value) {
			addCriterion("req_url <=", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlLike(String value) {
			addCriterion("req_url like", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlNotLike(String value) {
			addCriterion("req_url not like", value, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlIn(List<String> values) {
			addCriterion("req_url in", values, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlNotIn(List<String> values) {
			addCriterion("req_url not in", values, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlBetween(String value1, String value2) {
			addCriterion("req_url between", value1, value2, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqUrlNotBetween(String value1, String value2) {
			addCriterion("req_url not between", value1, value2, "reqUrl");
			return (Criteria) this;
		}

		public Criteria andReqTypeIsNull() {
			addCriterion("req_type is null");
			return (Criteria) this;
		}

		public Criteria andReqTypeIsNotNull() {
			addCriterion("req_type is not null");
			return (Criteria) this;
		}

		public Criteria andReqTypeEqualTo(String value) {
			addCriterion("req_type =", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeNotEqualTo(String value) {
			addCriterion("req_type <>", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeGreaterThan(String value) {
			addCriterion("req_type >", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeGreaterThanOrEqualTo(String value) {
			addCriterion("req_type >=", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeLessThan(String value) {
			addCriterion("req_type <", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeLessThanOrEqualTo(String value) {
			addCriterion("req_type <=", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeLike(String value) {
			addCriterion("req_type like", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeNotLike(String value) {
			addCriterion("req_type not like", value, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeIn(List<String> values) {
			addCriterion("req_type in", values, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeNotIn(List<String> values) {
			addCriterion("req_type not in", values, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeBetween(String value1, String value2) {
			addCriterion("req_type between", value1, value2, "reqType");
			return (Criteria) this;
		}

		public Criteria andReqTypeNotBetween(String value1, String value2) {
			addCriterion("req_type not between", value1, value2, "reqType");
			return (Criteria) this;
		}

		public Criteria andResResultIsNull() {
			addCriterion("res_result is null");
			return (Criteria) this;
		}

		public Criteria andResResultIsNotNull() {
			addCriterion("res_result is not null");
			return (Criteria) this;
		}

		public Criteria andResResultEqualTo(String value) {
			addCriterion("res_result =", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultNotEqualTo(String value) {
			addCriterion("res_result <>", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultGreaterThan(String value) {
			addCriterion("res_result >", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultGreaterThanOrEqualTo(String value) {
			addCriterion("res_result >=", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultLessThan(String value) {
			addCriterion("res_result <", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultLessThanOrEqualTo(String value) {
			addCriterion("res_result <=", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultLike(String value) {
			addCriterion("res_result like", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultNotLike(String value) {
			addCriterion("res_result not like", value, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultIn(List<String> values) {
			addCriterion("res_result in", values, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultNotIn(List<String> values) {
			addCriterion("res_result not in", values, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultBetween(String value1, String value2) {
			addCriterion("res_result between", value1, value2, "resResult");
			return (Criteria) this;
		}

		public Criteria andResResultNotBetween(String value1, String value2) {
			addCriterion("res_result not between", value1, value2, "resResult");
			return (Criteria) this;
		}

		public Criteria andParamIdIsNull() {
			addCriterion("param_id is null");
			return (Criteria) this;
		}

		public Criteria andParamIdIsNotNull() {
			addCriterion("param_id is not null");
			return (Criteria) this;
		}

		public Criteria andParamIdEqualTo(Integer value) {
			addCriterion("param_id =", value, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdNotEqualTo(Integer value) {
			addCriterion("param_id <>", value, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdGreaterThan(Integer value) {
			addCriterion("param_id >", value, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("param_id >=", value, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdLessThan(Integer value) {
			addCriterion("param_id <", value, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdLessThanOrEqualTo(Integer value) {
			addCriterion("param_id <=", value, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdIn(List<Integer> values) {
			addCriterion("param_id in", values, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdNotIn(List<Integer> values) {
			addCriterion("param_id not in", values, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdBetween(Integer value1, Integer value2) {
			addCriterion("param_id between", value1, value2, "paramId");
			return (Criteria) this;
		}

		public Criteria andParamIdNotBetween(Integer value1, Integer value2) {
			addCriterion("param_id not between", value1, value2, "paramId");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_req_url
     *
     * @mbggenerated do_not_delete_during_merge Sun May 21 15:45:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}