package com.longruan.zmsys.models;

public class ApiSysModule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys_module.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys_module.pid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys_module.sid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys_module.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys_module.des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys_module.orderid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Short orderid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys_module.id
	 * @return  the value of api_sys_module.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys_module.id
	 * @param id  the value for api_sys_module.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys_module.pid
	 * @return  the value of api_sys_module.pid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys_module.pid
	 * @param pid  the value for api_sys_module.pid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys_module.sid
	 * @return  the value of api_sys_module.sid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys_module.sid
	 * @param sid  the value for api_sys_module.sid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys_module.name
	 * @return  the value of api_sys_module.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys_module.name
	 * @param name  the value for api_sys_module.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys_module.des
	 * @return  the value of api_sys_module.des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys_module.des
	 * @param des  the value for api_sys_module.des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys_module.orderid
	 * @return  the value of api_sys_module.orderid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Short getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys_module.orderid
	 * @param orderid  the value for api_sys_module.orderid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setOrderid(Short orderid) {
		this.orderid = orderid;
	}
}