package com.longruan.zmsys.models;

public class ApiSys {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys.s_name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String sName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_sys.s_des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String sDes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys.id
	 * @return  the value of api_sys.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys.id
	 * @param id  the value for api_sys.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys.s_name
	 * @return  the value of api_sys.s_name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getsName() {
		return sName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys.s_name
	 * @param sName  the value for api_sys.s_name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setsName(String sName) {
		this.sName = sName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_sys.s_des
	 * @return  the value of api_sys.s_des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getsDes() {
		return sDes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_sys.s_des
	 * @param sDes  the value for api_sys.s_des
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setsDes(String sDes) {
		this.sDes = sDes;
	}
}