package com.longruan.zmsys.models;

import java.util.ArrayList;
import java.util.List;

public class ApiSysExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public ApiSysExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSNameIsNull() {
			addCriterion("s_name is null");
			return (Criteria) this;
		}

		public Criteria andSNameIsNotNull() {
			addCriterion("s_name is not null");
			return (Criteria) this;
		}

		public Criteria andSNameEqualTo(String value) {
			addCriterion("s_name =", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameNotEqualTo(String value) {
			addCriterion("s_name <>", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameGreaterThan(String value) {
			addCriterion("s_name >", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_name >=", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameLessThan(String value) {
			addCriterion("s_name <", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameLessThanOrEqualTo(String value) {
			addCriterion("s_name <=", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameLike(String value) {
			addCriterion("s_name like", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameNotLike(String value) {
			addCriterion("s_name not like", value, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameIn(List<String> values) {
			addCriterion("s_name in", values, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameNotIn(List<String> values) {
			addCriterion("s_name not in", values, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameBetween(String value1, String value2) {
			addCriterion("s_name between", value1, value2, "sName");
			return (Criteria) this;
		}

		public Criteria andSNameNotBetween(String value1, String value2) {
			addCriterion("s_name not between", value1, value2, "sName");
			return (Criteria) this;
		}

		public Criteria andSDesIsNull() {
			addCriterion("s_des is null");
			return (Criteria) this;
		}

		public Criteria andSDesIsNotNull() {
			addCriterion("s_des is not null");
			return (Criteria) this;
		}

		public Criteria andSDesEqualTo(String value) {
			addCriterion("s_des =", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesNotEqualTo(String value) {
			addCriterion("s_des <>", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesGreaterThan(String value) {
			addCriterion("s_des >", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesGreaterThanOrEqualTo(String value) {
			addCriterion("s_des >=", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesLessThan(String value) {
			addCriterion("s_des <", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesLessThanOrEqualTo(String value) {
			addCriterion("s_des <=", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesLike(String value) {
			addCriterion("s_des like", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesNotLike(String value) {
			addCriterion("s_des not like", value, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesIn(List<String> values) {
			addCriterion("s_des in", values, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesNotIn(List<String> values) {
			addCriterion("s_des not in", values, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesBetween(String value1, String value2) {
			addCriterion("s_des between", value1, value2, "sDes");
			return (Criteria) this;
		}

		public Criteria andSDesNotBetween(String value1, String value2) {
			addCriterion("s_des not between", value1, value2, "sDes");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_sys
     *
     * @mbggenerated do_not_delete_during_merge Sun May 21 15:45:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}