package com.longruan.zmsys.models;

public class ApiUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.no
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.teamid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer teamid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.loginname
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String loginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.password
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.sex
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.email
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.typeofwork
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String typeofwork;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.typeofperson
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer typeofperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.islock
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String islock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.isdel
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String isdel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.phone
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user.mobile
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String mobile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.id
	 * @return  the value of api_user.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.id
	 * @param id  the value for api_user.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.no
	 * @return  the value of api_user.no
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.no
	 * @param no  the value for api_user.no
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.teamid
	 * @return  the value of api_user.teamid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getTeamid() {
		return teamid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.teamid
	 * @param teamid  the value for api_user.teamid
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setTeamid(Integer teamid) {
		this.teamid = teamid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.name
	 * @return  the value of api_user.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.name
	 * @param name  the value for api_user.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.loginname
	 * @return  the value of api_user.loginname
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.loginname
	 * @param loginname  the value for api_user.loginname
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.password
	 * @return  the value of api_user.password
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.password
	 * @param password  the value for api_user.password
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.sex
	 * @return  the value of api_user.sex
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.sex
	 * @param sex  the value for api_user.sex
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.email
	 * @return  the value of api_user.email
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.email
	 * @param email  the value for api_user.email
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.typeofwork
	 * @return  the value of api_user.typeofwork
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getTypeofwork() {
		return typeofwork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.typeofwork
	 * @param typeofwork  the value for api_user.typeofwork
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setTypeofwork(String typeofwork) {
		this.typeofwork = typeofwork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.typeofperson
	 * @return  the value of api_user.typeofperson
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getTypeofperson() {
		return typeofperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.typeofperson
	 * @param typeofperson  the value for api_user.typeofperson
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setTypeofperson(Integer typeofperson) {
		this.typeofperson = typeofperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.islock
	 * @return  the value of api_user.islock
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getIslock() {
		return islock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.islock
	 * @param islock  the value for api_user.islock
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setIslock(String islock) {
		this.islock = islock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.isdel
	 * @return  the value of api_user.isdel
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.isdel
	 * @param isdel  the value for api_user.isdel
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setIsdel(String isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.phone
	 * @return  the value of api_user.phone
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.phone
	 * @param phone  the value for api_user.phone
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user.mobile
	 * @return  the value of api_user.mobile
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user.mobile
	 * @param mobile  the value for api_user.mobile
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
}