package com.longruan.zmsys.models;

public class ApiUserTeam {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user_team.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user_team.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column api_user_team.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user_team.id
	 * @return  the value of api_user_team.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user_team.id
	 * @param id  the value for api_user_team.id
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user_team.name
	 * @return  the value of api_user_team.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user_team.name
	 * @param name  the value for api_user_team.name
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column api_user_team.remark
	 * @return  the value of api_user_team.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column api_user_team.remark
	 * @param remark  the value for api_user_team.remark
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}