package com.longruan.zmsys.dao;

import com.longruan.zmsys.models.ApiError;
import com.longruan.zmsys.models.ApiErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiErrorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int countByExample(ApiErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByExample(ApiErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insert(ApiError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insertSelective(ApiError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	List<ApiError> selectByExample(ApiErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	ApiError selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ApiError record,
			@Param("example") ApiErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExample(@Param("record") ApiError record,
			@Param("example") ApiErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKeySelective(ApiError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_error
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKey(ApiError record);
}