package com.longruan.zmsys.dao;

import com.longruan.zmsys.models.ApiReqUrl;
import com.longruan.zmsys.models.ApiReqUrlExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ApiReqUrlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int countByExample(ApiReqUrlExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByExample(ApiReqUrlExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insert(ApiReqUrl record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insertSelective(ApiReqUrl record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	List<ApiReqUrl> selectByExample(ApiReqUrlExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	ApiReqUrl selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ApiReqUrl record,
			@Param("example") ApiReqUrlExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExample(@Param("record") ApiReqUrl record,
			@Param("example") ApiReqUrlExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKeySelective(ApiReqUrl record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_url
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKey(ApiReqUrl record);
	/**
	 * 分页查询API路径总数
	 * @param pageing
	 * @return
	 */
	int findReqUrlCountByConditions(Map<String, Object> paramMap);
	/**
	 * 分页查询API路径信息
	 * @param pageing
	 * @return
	 */
	List<Map<String,Object>> findReqUrlPageByConditions(Map<String, Object> paramMap);
	/**
	 * 心一：查看菜单下的请求信息
	 * @param moduleId
	 * @return
	 */
	List<Map<String,Object>> findApiReqUrlListByModuleId(String moduleId);

}