package com.longruan.zmsys.dao;

import com.longruan.zmsys.models.ApiReqParam;
import com.longruan.zmsys.models.ApiReqParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiReqParamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int countByExample(ApiReqParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByExample(ApiReqParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insert(ApiReqParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insertSelective(ApiReqParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	List<ApiReqParam> selectByExample(ApiReqParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	ApiReqParam selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ApiReqParam record,
			@Param("example") ApiReqParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExample(@Param("record") ApiReqParam record,
			@Param("example") ApiReqParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKeySelective(ApiReqParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_req_param
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKey(ApiReqParam record);
}