package com.longruan.zmsys.dao;

import com.longruan.zmsys.models.ApiSysModule;
import com.longruan.zmsys.models.ApiSysModuleExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ApiSysModuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int countByExample(ApiSysModuleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByExample(ApiSysModuleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insert(ApiSysModule record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insertSelective(ApiSysModule record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	List<ApiSysModule> selectByExample(ApiSysModuleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	ApiSysModule selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ApiSysModule record,
			@Param("example") ApiSysModuleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExample(@Param("record") ApiSysModule record,
			@Param("example") ApiSysModuleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKeySelective(ApiSysModule record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys_module
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKey(ApiSysModule record);
	/**
	 * 心一：条件查询集合信息
	 * @param paraMap
	 * @return
	 */
	List<Map<String, Object>> findSysModuleList(Map<String, Object> paraMap);
	/**
	 * 心一：根据父节点查询子节点
	 * @param paraMap
	 * @return
	 */
	List<Map<String, Object>> findMapListByPId(Integer pid);
	/**
	 * 心一：查询最大排序值
	 * @param pid
	 * @return
	 */
	int findMaxOrderIdByPid(Integer pid);
	

	
	
}