package com.longruan.zmsys.dao;

import com.longruan.zmsys.models.ApiSys;
import com.longruan.zmsys.models.ApiSysExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ApiSysMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int countByExample(ApiSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByExample(ApiSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insert(ApiSys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insertSelective(ApiSys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	List<ApiSys> selectByExample(ApiSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	ApiSys selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ApiSys record,
			@Param("example") ApiSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExample(@Param("record") ApiSys record,
			@Param("example") ApiSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKeySelective(ApiSys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_sys
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKey(ApiSys record);

	/**
	 * 心一:全查询系统列表
	 * @param pageing
	 * @return
	 */
	List<Map<String,Object>> findSysListByConditions(Map<String, Object> paramMap);
}