package com.longruan.zmsys.dao;

import com.longruan.zmsys.models.ApiUser;
import com.longruan.zmsys.models.ApiUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int countByExample(ApiUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByExample(ApiUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insert(ApiUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int insertSelective(ApiUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	List<ApiUser> selectByExample(ApiUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	ApiUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ApiUser record,
			@Param("example") ApiUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByExample(@Param("record") ApiUser record,
			@Param("example") ApiUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKeySelective(ApiUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_user
	 * @mbggenerated  Thu Jun 01 08:56:08 CST 2017
	 */
	int updateByPrimaryKey(ApiUser record);
}